#!/usr/bin/env python3
"""Generate per-brick indexes of the ADRs that affect each brick.

Reads the `affects` field of every ADR and writes one Markdown file per brick
under docs/adr/index/, so you can see at a glance which decisions touch a brick
without grepping. Also writes index/README.md with the full list.

The files under docs/adr/index/ are generated output. Do not edit them by hand;
run this script (or let pre-commit run it) to refresh them.

Run it yourself any time:
    python scripts/checks/adr_index.py
"""
from __future__ import annotations

import re
from collections import defaultdict
from pathlib import Path
from typing import Any

import yaml  # installed for this check by pre-commit / CI

ADR_DIR = Path("docs/adr")
INDEX_DIR = ADR_DIR / "index"
TEMPLATE = "0000-adr-template.md"
TITLE_RE = re.compile(r"^#\s+(.*)$", re.MULTILINE)
GENERATED_NOTE = "_Generated by scripts/checks/adr_index.py. Do not edit by hand._"


def parse(path: Path) -> tuple[dict[str, Any], str]:
    text = path.read_text(encoding="utf-8")
    data = {}
    if text.startswith("---"):
        parts = text.split("---", 2)
        if len(parts) >= 3:
            try:
                data = yaml.safe_load(parts[1]) or {}
            except yaml.YAMLError:
                data = {}
    title_match = TITLE_RE.search(text)
    title = title_match.group(1).strip() if title_match else path.stem
    return data, title


def line(entry: tuple[str, str, str], rel: str) -> str:
    name, title, status = entry
    suffix = f" ({status})" if status else ""
    return f"- [{title}]({rel}{name}){suffix}"


def main() -> int:
    if not ADR_DIR.is_dir():
        print("No docs/adr/ directory, nothing to index.")
        return 0

    by_brick: defaultdict[tuple[str, str], list[tuple[str, str, str]]] = defaultdict(list)
    all_adrs: list[tuple[str, str, str]] = []

    for path in sorted(ADR_DIR.glob("*.md")):
        if path.name == TEMPLATE or path.name.lower() == "readme.md":
            continue
        data, title = parse(path)
        entry = (path.name, title, str(data.get("status", "")).strip())
        all_adrs.append(entry)
        affects = data.get("affects") or {}
        if isinstance(affects, dict):
            for kind in ("components", "bases", "projects"):
                for brick in affects.get(kind) or []:
                    by_brick[(kind, brick)].append(entry)

    INDEX_DIR.mkdir(parents=True, exist_ok=True)
    for old in INDEX_DIR.glob("*.md"):
        old.unlink()

    for (kind, brick), entries in sorted(by_brick.items()):
        safe = "_all_" if brick == "*" else brick
        body = [f"# ADRs affecting {kind[:-1]}: {brick}"]
        body += [line(e, "../") for e in entries]
        body += ["", GENERATED_NOTE]
        (INDEX_DIR / f"{kind}-{safe}.md").write_text("\n".join(body) + "\n", encoding="utf-8")

    readme = [
        "# ADR index",
        "Generated view of the decision log. Do not edit by hand; run "
        "`python scripts/checks/adr_index.py`.",
        "",
        "## All ADRs",
    ]
    readme += [line(e, "../") for e in all_adrs]
    readme += ["", "## By brick"]
    for (kind, brick), entries in sorted(by_brick.items()):
        safe = "_all_" if brick == "*" else brick
        readme.append(
            f"- {kind[:-1]} `{brick}`: [{kind}-{safe}.md]({kind}-{safe}.md) "
            f"({len(entries)})"
        )
    readme.append("")
    (INDEX_DIR / "README.md").write_text("\n".join(readme), encoding="utf-8")

    print(f"Wrote index for {len(all_adrs)} ADR(s) across {len(by_brick)} brick view(s).")
    return 0


if __name__ == "__main__":
    raise SystemExit(main())
